"use client";

import { useTranslations } from "next-intl";
import ApexChart from "react-apexcharts";
import { ApexOptions } from "apexcharts";
import Card from "@mui/material/Card";
import dayjs from "dayjs";

import { DATE_FORMAT } from "../constants";

const ProfitGeneratedByProduct = () => {
  const t = useTranslations();

  const startDate = dayjs().subtract(30, "days").format(DATE_FORMAT);
  const endDate = dayjs().format(DATE_FORMAT);

  const data = {
    Bikini: {
      profit: 700,
      sales: 600,
    },
    Swimsuit: {
      profit: 90,
      sales: 80,
    },
    Sunglasses: {
      profit: 350,
      sales: 200,
    },
    Sunscreen: {
      profit: 290,
      sales: 150,
    },
    "Beach Towel": {
      profit: 100,
      sales: 50,
    },
  };

  const options: ApexOptions = {
    tooltip: {
      shared: true,
      intersect: false,
      followCursor: true,
    },
    title: {
      text: t("Profit generated by product"),
      style: {
        fontSize: "24px",
      },
    },
    xaxis: {
      categories: Object.keys(data),
    },
    labels: Object.keys(data),
    subtitle: {
      text: `${t("From")} ${startDate} ${t("to")} ${endDate}`,
      style: {
        fontSize: "14px",
      },
    },
    plotOptions: {
      bar: {
        barHeight: "60%",
        horizontal: true,
        borderRadius: 2,
      },
    },
    dataLabels: {
      enabled: false,
    },
    yaxis: {
      min: 0,
    },
  };

  const series = [
    {
      name: t("Profit"),
      data: Object.values(data).map(d => d.profit),
    },
    {
      name: t("Sales"),
      data: Object.values(data).map(d => d.sales),
    },
  ];

  return (
    <Card className="col-start-2 col-end-4">
      <ApexChart type="bar" options={options} series={series} height={300} />
    </Card>
  );
};

export { ProfitGeneratedByProduct };
